version: "3.7"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - LPORT=${l_port}
        - TeamServer=${team_server}
        - DOMAIN_NAME=${domain_name}
    ports:
      - ${l_port}:${l_port}
    volumes:
        - /certs/letsencrypt/live/${domain_name}/privkey.pem:/etc/nginx/ssl/privkey.pem
        - /certs/letsencrypt/live/${domain_name}/fullchain.pem:/etc/nginx/ssl/fullchain.pem
